import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/sections/Banner";
import Skills from '../components/sections/Skills';
import Projects from '../components/sections/Projects';
import Form from "../components/sections/Form";
import Footer from '../components/layout/Footer';

export default function Home() {
  return (
    <div className={`${styles.container}`}>
      <Head>
        <title>Racker Agency | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Skills />
      <Projects />
      <Form />
    </div>
  )
}
